# USDA Food Database
This is an analysis that delves into the database provided by the US Department of Agriculture. It provides nutritional information for a plethora of food options in JSON format. If there are any questions or concerns the author may be contacted to discuss analysis and methodology.

In [8]:
# Start with imports
import json
import pandas as pd

Create a database from the json file:

In [12]:
db = json.load(open('database.json'))

In [15]:
# Preview the basics of the data
len(db)

6636

Find the keys at [0]:

In [19]:
db[0].keys()

dict_keys(['id', 'description', 'tags', 'manufacturer', 'group', 'portions', 'nutrients'])

Now find the nutrients key value pairs:

In [23]:
db[0]['nutrients'][0]

{'value': 25.18,
 'units': 'g',
 'description': 'Protein',
 'group': 'Composition'}

Create a DataFrame called nutrients that holds a dictionary of nutrients held at db[0]:

In [34]:
nutrients = pd.DataFrame(db[0]['nutrients'])

Gather nutritional data from our records into a single DataFrame where the rows link to the original nutitional information from the id column:

In [44]:
nutrients = []
for rec in db:
    fnuts = pd.DataFrame(rec['nutrients'])
    fnuts['id'] = rec['id']
    nutrients.append(fnuts)
nutrients = pd.concat(nutrients, ignore_index=True)

In [46]:
# Preview a bit of the data
nutrients[:7]

     value units                  description        group    id
0    25.18     g                      Protein  Composition  1008
1    29.20     g            Total lipid (fat)  Composition  1008
2     3.06     g  Carbohydrate, by difference  Composition  1008
3     3.28     g                          Ash        Other  1008
4   376.00  kcal                       Energy       Energy  1008
5    39.28     g                        Water  Composition  1008
6  1573.00    kJ                       Energy       Energy  1008

Convert the list of dicts to a dataframe, making sure to specify the list of fields to extract:

In [51]:
info_keys = ['description', 'group', 'id', 'manufacturer']

In [56]:
# Create a new DataFrame 
info = pd.DataFrame(db, columns=info_keys)

In [58]:
# Preview the data 
info[:5]

,description,group,id,manufacturer
0,"Cheese, caraway",Dairy and Egg Products,1008,
1,"Cheese, cheddar",Dairy and Egg Products,1009,
2,"Cheese, edam",Dairy and Egg Products,1018,
3,"Cheese, feta",Dairy and Egg Products,1019,
4,"Cheese, mozzarella, part skim milk",Dairy and Egg Products,1028,